deployment:
  name: ratingsweb-deploy
  namespace: aks-workshop-qa
  labels:
    app: ratingsweb-deploy
  selectorLabels:
    app: ratingsweb-pod
    versionb: v1
  replicas: 1
  strategyType: RollingUpdate
  maxSurge: 1
  maxUnavailable: 1
  nodeSelector:
    agentpool: agentpool
  imagePullSecrets:
  - name: aks-acr-secret
  containers:
  - name: ratingsweb-app
    image: akswkshpacr.azurecr.io/ratings-web:v1.0.0
    imagePullPolicy: IfNotPresent
    readinessPort: 8080
    readinessPath: /healthz
    livenessPort: 8080
    livenessPath: /healthz
    memoryRequest: "64Mi"
    cpuRequest: "250m"
    memoryLimit: "512Mi"
    cpuLimit: "500m"
    containerPorts: [8080]    
    env:
    - name: API
      value: http://ratingsapi-service.aks-workshop-qa.svc         
    ports:
    - containerPort: 8080
service:
  name: ratingsweb-service
  namespace: aks-workshop-qa
  selector:
    app: ratingsweb-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    name: http
    targetPort: 8080